name: Hourly Weather Bot Trigger

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

jobs:
  call_vercel_endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron Job URL
        run: curl -f "${{ secrets.VERCEL_CRON_URL }}"
